allowBuilds:
  '@nuxt4-layers/theme-manager@git+https://github.com/nuxt4-layers/theme-manager.git': true
  '@parcel/watcher': false
  '@tailwindcss/oxide': false
  esbuild: false
  unrs-resolver: false
  vue-demi: false